# Generated by Django 3.1.3 on 2020-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_ban',
            field=models.BooleanField(default=False),
        ),
    ]
